# 线上配置文件
# @author kang
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8102
  servlet:
    context-path: /api
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kang_so?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 10.0.12.17
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://10.0.12.17:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
canal:
  destination: example
  server: 10.0.12.17:11111
#elastic
#action:
#  auto_create_index: true
#canal:
#  client:
#    instances:
#      example:
#        host: localhost
#        port: 8101
#        batchSize: 1000
#        userName: 
#        password: 
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: test
    secretKey: AKIDRmy0rZ6TgaXREpS6fK6kAQYZRCtRly4O
    region: test
    bucket: test